### ISSUE TITLE
[ Epic ] Web3Inbox milestone 3

### ISSUE THREAD

**Issue by devceline** [WalletConnect/web3inbox#105]
# Depends on
- [x] #116 
# React  Native SDK
- [x] https://github.com/WalletConnect/web3inbox/issues/126

# Push Features
- [x] #97 
- [x] #107  
- [x] Finalize `wc_pushSubscribe`
  - [x] JS
  - [x] Kotlin
  - [x] Swift

# Ready for verified dapps
- [ ] Support did documents in chat client
  - [ ] https://github.com/WalletConnect/chat-client-js/issues/50 (JS)
  - [ ] Kotlin
  - [ ] Swift
- [ ] Design unified UI
- [ ] Implement unified UI

# Nice to have
- [x] Create settings controller in web3inbox
- [x] Create auth controller in web3inbox
- [ ] Add communication with w3i-sdk settings controller
  - [ ] React Native
  - [ ] Swift
  - [ ] iOS
- [x] #106
- [ ] #113
