### ISSUE TITLE
[ Epic ] Web3Inbox Foundation (Sync & History)

### ISSUE THREAD

**Issue by devceline** [WalletConnect/web3inbox#116]
# Web3Inbox Foundation
## Chat & Notify
- [x] Create History Client
  - [x] https://github.com/WalletConnect/walletconnect-utils/issues/95 (JS)
  - [x] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/950 (Kotlin)
  - [x] Swift
- [x] Update History API authentication 
  - [x] Rust
- [x] Create sync client
  - [x] JS
  - [x] Kotlin
  - [x] Swift
- [x] (JS) Make sync client inject-able through the constructor, not part of the notify and chat clients  

## Chat
- [x] (JS, Swift, Kotlin) Run cross-platform tests for chat/sync

## Notify
- [x] Add sync to notify client
  - [x] JS
  - [x] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/952 (Kotlin)
  - [x] Swift
- [x] (JS, Swift, Kotlin) Run cross-platform tests for notify/sync
