### ISSUE TITLE
[ Epic ] Web3Inbox React Native SDK

### ISSUE THREAD

**Issue by devceline** [WalletConnect/web3inbox#126]
# React Native SDK

## Setup
- [x] Initialize web3inbox react native [test branch](https://github.com/WalletConnect/react-native-examples/pull/35)
- [x] Install latest `@walletconnect/chat-client`
- [x] Install latest `@walletconnect/push-client`

## Rendering
- [x] Create component to allow rendering web3inbox as a webview [W3InboxModal.tsx](https://github.com/WalletConnect/react-native-examples/blob/c56db52bcd94529d4918efefb99251d329b14b8d/wallets/rn_cli_wallet/src/components/Modals/W3InboxModal.tsx)
- [x] Make it render web3inbox through the url: https://web3inbox-dev-hidden.vercel.app/
- [x] Attach relevant query params:
  - chatProvider=reactnative (Tom has uncommented chatProvider + here is most of the [setup](https://github.com/WalletConnect/react-native-examples/blob/c56db52bcd94529d4918efefb99251d329b14b8d/wallets/rn_cli_wallet/src/components/Modals/W3InboxModal.tsx) )
  - pushProvider=reactnative
  - authProvider=reactnative

## Authentication logic
- [x] Setting initial account can be done by setting `account` query param, matching `account=<ETH-ADDRESS>`

## Communication logic
- [x] Inject [JS into webview](https://idanlevi2.medium.com/injecting-javascript-into-react-native-webview-521e4e55964b) to allow web3inbox to communicate with RN SDK
  - Should inject the method here: `window.ReactNativeWebview.postMessage`
- [x] Create util to send messages to web3inbox
  - chat messages should go through `window.web3inbox.chat`
  - notify messages should go through `window.web3inbox.push`

## Methods
- [x] Proxy all the methods in chat facade, [starting here](https://github.com/WalletConnect/web3inbox/blob/main/src/w3iProxy/w3iChatFacade.ts#L185) and [ending here](https://github.com/WalletConnect/web3inbox/blob/main/src/w3iProxy/w3iChatFacade.ts#L284)
- [x] Proxy all methods in push facade, [starting here](https://github.com/WalletConnect/web3inbox/blob/main/src/w3iProxy/w3iChatFacade.ts#L284) and [ending here](https://github.com/WalletConnect/web3inbox/blob/main/src/w3iProxy/w3iPushFacade.ts#L85)

## Add logic to enable or disable pages
- [x] Add props to the react native component to enable or disable pages
  - props: 
    - chatEnabled: `boolean`
    - pushEnabled: `boolean`
    - settingsEnabled: `boolean`
  - the props default to `true`
  - the props directly translate to query params, eg `chatEnabled=true`
