### ISSUE TITLE
beta UI/UX improvements for app.web3inbox.com

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3inbox#244]
```[tasklist]
### Tasks
- [ ] https://github.com/WalletConnect/web3inbox/issues/251
- [ ] https://github.com/WalletConnect/web3inbox/issues/252
- [ ] https://github.com/WalletConnect/web3inbox/issues/253
- [ ] https://github.com/WalletConnect/web3inbox/issues/254
- [ ] https://github.com/WalletConnect/web3inbox/issues/256
- [ ] https://github.com/WalletConnect/web3inbox/issues/257
- [ ] https://github.com/WalletConnect/web3inbox/issues/260
- [ ] https://github.com/WalletConnect/web3inbox/issues/246
- [ ] https://github.com/WalletConnect/web3inbox/issues/280
- [ ] https://github.com/WalletConnect/web3inbox/issues/293
- [ ] https://github.com/WalletConnect/web3inbox/issues/282
- [ ] https://github.com/WalletConnect/web3inbox/issues/296
- [x] P1: show more not tuned: https://walletconnect.slack.com/archives/C044SKFKELR/p1701985382474109
- [ ] https://github.com/WalletConnect/web3inbox/issues/290
- [ ] https://github.com/WalletConnect/web3inbox/issues/283
- [x] P3: refreshing on mobile when on notifications screen (not a dApp) takes you to discover page
- [ ] https://github.com/WalletConnect/web3inbox/issues/281
```

**Comment by herrhaase** [comment]
<img width="904" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/22012841-033d-4036-9412-8c3a2ead921e">

**Comment by enesozturk** [comment]
> P3: refreshing on mobile when on notifications screen (not a dApp) takes you to discover page

This should already be fixed with previous updates. Also, we're forcing users to install PWA on mobile and this doesn't see reproducible there. Checking as completed
