### ISSUE TITLE
Improve Connect page

### ISSUE THREAD

**Issue by herrhaase** [WalletConnect/web3inbox#251]
```[tasklist]
### Tasks
- [ ] 1. Update the logo to the light blue version
- [ ] 2. Remove hover state on logo
- [ ] 3. Add sidebar icons for logged out state
- [ ] 4. Adjust letter-spacing of subline and button to "-0.2px"
```

**Comment by herrhaase** [comment]
<img width="904" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/0595baa3-7081-415c-8712-517b070fc27a">

For more details, go here https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=3380%3A25785&mode=design&t=GjGyoFpkSxHLAejx-1
