### ISSUE TITLE
Improve Signature page

### ISSUE THREAD

**Issue by herrhaase** [WalletConnect/web3inbox#252]
```[tasklist]
### Tasks
- [x] 1. UX: When showing "Sign in to enable notifications" overlay, don't show any app UI in the background other than the sidebar UI elements (P1)
- [x] 2. Change overlay color as in design (P2)
- [ ] 4. Adjust letter-spacing (P2)
- [x] 5. Update the modal UI for the 2nd step "Requesting sign-in" as in the design (P2)
```

**Comment by herrhaase** [comment]
<img width="1687" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/1d687419-3cf3-4cf4-a972-b17f90086332">

Find details **[here](https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=3390%3A31600&mode=design&t=GjGyoFpkSxHLAejx-1)**

**Comment by herrhaase** [comment]
**Update:**

Signature request modals will now also feature an "X" button to allow the user to disconnect their wallets and cancel the request process 

<img width="742" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/3b9a6a92-aaa4-4cd3-8f51-37d9dee80d99">

https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=2620%3A86915&mode=design&t=DleDZQtnaHtsaKML-1

**Comment by enesozturk** [comment]
> 4. Adjust letter-spacing (P2)

Let's handle this once we update the font to Inter in the Figma. I want to check all the text variants

> 5. Update the modal UI for the 2nd step "Requesting sign-in" as in the design (P2)

This and the others should be fixed now. The only thing: In the design, the loading indicator has a linear-gradient as a color, this might be a bit tricky in CSS, need to invest more time to do it. Let's handle it later. Or we could what we have now (same with w3m loading indicators)


@chris13524 I think we could move 4. to another ticket and close this one, wdyt?

**Comment by chris13524** [comment]
@enesozturk 

Wallet icon is black insetad of white
<img width="395" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/1979423/effaeec5-b6b1-43bd-9704-9fe8deaaefee">

Waiting for wallet button is white instead of blue
<img width="395" alt="Screenshot 2023-12-01 at 14 46 16" src="https://github.com/WalletConnect/web3inbox/assets/1979423/8fb566ec-119b-444e-b308-e8113b3380c0">

**Comment by enesozturk** [comment]
@chris13524 Should be fixed now

**Comment by chris13524** [comment]
Beautiful!
