### ISSUE TITLE
Improve Discover page

### ISSUE THREAD

**Issue by herrhaase** [WalletConnect/web3inbox#254]
```[tasklist]
### Tasks
- [x] Add blue highlight indicator on "Inbox" pages
- [x] Rename labels from "Explore" to "Discover" and "Discover all apps"
- [x] Remove the 2nd "subscribe" button at the top right
- [x] Change "gm!" to "GM Dapp": https://github.com/WalletConnect/gm-dapp/pull/27
- [x] Update GM icon (see below): https://github.com/WalletConnect/gm-dapp/pull/27
- [ ] Remove "official" badge (blue check) from any app not maintained by WalletConnect
- [x] Show app domain for any non-official app (see iOS screenshot below)
- [x] Fix card backgrounds (see below)
- [x] Fix Search bar (see below)
- [x] Center content in content area (see below)
- [x] Fix card width to be equal (see below)
- [x] Fix UI bug on 700px width (see below)
- [x] Fix Subscribe button behaviour (see below)
- [x] ❌ Bug: Fix subscribe button (see below)
- [x] When subscribed, make app card tappable
```
<img width="705" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/82f7155d-11a0-40e3-927e-947e8350a920">

**Comment by herrhaase** [comment]
**Gm Icon**

Please use this everywhere

![GM-icon@2x](https://github.com/WalletConnect/web3inbox/assets/707251/23c5f9f6-e9c3-4c01-9ac3-c24cff7622d8)
![GM-icon](https://github.com/WalletConnect/web3inbox/assets/707251/0e6e026e-028d-4093-a62b-64c068052bff)

**Comment by herrhaase** [comment]
**Fix card backgrounds**

2 options:

A) we extract the most prominent color value out of the avatar and use this in a radial gradient from [extracted color] to #FFF, wih a gradient opacity of 10% on a full white (#FFF) background – or 

B) we use the avatar, resize it, blur it with "filter:blur (120px)" and an opacity of 10% on a full white (#FFF) background. 

I advocate for option B, as it should give us more detailed results.

<img width="1621" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/6c4b4867-ea27-41bc-a834-bee0fb2cfe51">

See details [here](https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=3390%3A51499&mode=dev)

**Comment by herrhaase** [comment]
**Fix search bar** 

<img width="446" alt="Screenshot 2023-10-10 at 18 19 47" src="https://github.com/WalletConnect/web3inbox/assets/707251/006c41bb-d9ba-4f0e-a5ce-70a6479b948a">

When subscribed to "gm!" and searching for "Gm" the search filters out the app I am subscribed to. This is counterintuitive to most search bars and therefore we should make the search smarter by allowing the following scenarios:

- ignore spelling of lowercase / uppercase -> any case returns a result if matching
- if any part of the string matches we input we return a result
- if any part of the description matches the input, return as a results (although less prominently sorted)

**Comment by herrhaase** [comment]
**Center content in content area & fix card width**

<img width="1682" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/2f99813c-580e-4929-9f60-9b9763797fb1">

**Comment by herrhaase** [comment]
**Fix UI bug on 700px width**

<img width="741" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/c6180286-c4cd-4e19-b87e-1a73199bfe1f">

**Comment by herrhaase** [comment]
**Fix Subscribe button behaviour**

When I can't subscribe to a dapp (for whatever reason) the UI button becomes white and the label disappears. Instead of this behaviour, the button should only change when a user is successfully subscribed. 

Should it take a while to retrieve a successful subscription, we might want to show a white spinner inside the blue button until then, which **returns the button to its blue normal state** should we not be able to subscribe a user to the dapp.

https://github.com/WalletConnect/web3inbox/assets/707251/d3c129ed-2a51-407e-9344-f11d16379e82

**Comment by herrhaase** [comment]
**❌ Bug: Fix subscribe button**

The button doesn't seem to pick up on my active subscription

<img width="756" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/000a5162-7178-436b-8c00-26d08f62c154">
