### ISSUE TITLE
Improve Notifications Sidebar

### ISSUE THREAD

**Issue by herrhaase** [WalletConnect/web3inbox#256]
```[tasklist]
### Tasks
- [x] Adjust sidebar length to 320px (fixed) (P2)
- [x] Truncate long dapp names (P1)
- [x] Make hover animation more snappier (P2)
```

**Comment by herrhaase** [comment]
<img width="883" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/2b95312c-28bf-4e2a-bb2f-141aef009511">

Instead of being responsive, the Notifications sidebar should be always **fixed at 320px.** Longer app names should be truncated. 

<img width="381" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/2917338b-7617-49b4-ab8e-243211e38407">

**Comment by herrhaase** [comment]
**Make hover animation more snappier** 

https://github.com/WalletConnect/web3inbox/assets/707251/26ec620c-c1cf-4b02-a79c-089223275b09

Current animation feels quite slow. Can we reduce duration to 300ms and see how that feels?

**Comment by enesozturk** [comment]
@chris13524 @chadyj The tasks in this ticket are also fixed.

**Comment by chris13524** [comment]
LGTM. Closing
