### ISSUE TITLE
Improve Notifications page

### ISSUE THREAD

**Issue by herrhaase** [WalletConnect/web3inbox#257]
```[tasklist]
### Tasks
- [ ] Fix font styles (see below) (P2)
- [x] Fix "Show more" (see below) (P0)
- [ ] Fix hover states (see below) (P2)
- [x] Update placeholder icon (see below) (P1)
- [x] Ensure every app has a name (see below)
- [x] Ensure selection style is always on light theme (see below) (P2)
- [ ] Improve empty state (see below) [Update picture to standard, use new copy] (p2)
- [ ] Improve Unsubscribe Modal (p2)
- [ ] Improve settings dropdown (p2)
```

**Comment by herrhaase** [comment]
**Fix font styles**

<img width="850" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/7120c996-7b2e-4ab8-b343-5c5c72c726e6">

See details [here](https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=3380%3A3198&mode=design&t=EAfRQa8hP0MiqKeC-1)

**Comment by herrhaase** [comment]
**Fix "Show more"**

1. Doesnt always show up – should be always visible.
2. Doesnt work when clicking on it.

**Comment by herrhaase** [comment]
**Fix hover states**

<img width="1399" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/eda7cc4d-49fa-44e2-8806-34daa9a48468">

**Comment by herrhaase** [comment]
**Update placeholder icon**

<img width="922" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/6b1ec1de-9d35-4d3c-bdd3-8a9150deae1e">

https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=3432%3A65755&mode=design&t=ZDISUYI7cDwGsmmq-1

**Comment by herrhaase** [comment]
**Ensure every app has a name**

<img width="1449" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/abf29ed9-3ed9-48a1-a2c0-ce2e07b56668">

Pancake's staging integration currently does not have a name that is displayed. Until Cloud is ready to allow projects to manage their app we should force a name in the UI. This could be as simply as the app's ID.

**Comment by herrhaase** [comment]
**Ensure selection style is always on light theme**

<img width="597" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/bbb06e28-7cd3-4f48-b8fd-67c2e4339995">

When my system switches to Dark Mode the UI is still Light, but the selector style is switched to Dark Mode, resulting in weird selection styling. Lets make sure UI is always in Light until we have full Dark Mode support.

**Comment by herrhaase** [comment]
**Improve empty state**

<img width="689" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/6ee22093-2e15-460c-8ca4-df31845e9a05">

1. First of all, if we would send a standardised "Welcome to [dapp name]." notification immediately after someone subscribes to a channel, then we actually don't need this state, because there will be always one notification available – so this is something to consider.

<img width="456" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/fdb61ead-b1a7-4364-ad22-0fe330b8be3e">

2. Otherwise, this state can be improved two-fold: First, I would like to make the background gradient avatar-independent, so that it always looks the same, as dark avatars make it look bad. You can use this asset [here](https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=2620%3A98911&mode=design&t=KXJ0vH3LTti0afI6-1) and then overlay the avatar on top of the circle with a separate layer.

3. The copy should say "All new notifications will appear here."

**Comment by herrhaase** [comment]
**Change all default notification images to app avatar**

Not sure why I didn't see this earlier (lol), but please change the img for each notification to the app's avatar as the default img. Projects are able to specify different images per notification category, but if no category or different img is specified, we always default to the app's avatar.

<img width="1298" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/002beb54-dda5-48e5-aed8-e2e90f2f3c04">

**Comment by herrhaase** [comment]
**Improve Unsubscribe Modal**

- [ ] check "X" icon matches with Web3Modal integration
- [ ] Update error color to #ED4747 (globally)
- [ ] Update button label to "Unsubscribe"

<img width="1566" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/19df6aa9-f180-46f9-91f1-951906c890a0">

**Comment by herrhaase** [comment]
**Improve settings dropdown**

- [ ] Keep hover state of "..." visible / active when dropdown is active

<img width="245" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/a10cc23d-835f-42c3-b905-6bffd7e7b6f5">

- [ ] Update error color for "X Unsubscribe" to #ED4747 (globally)

- [ ] Can't really reproduce this anymore, but saw this active state on Chrome the other day and then it stayed like this when the modal was open. Lets make sure that we hide these states with CSS or otherwise at least display them properly 
<img width="190" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/a6bacf04-c2e5-43b6-ae4c-c56bb88984c7">
